import { FlawedQuestion } from '../types';

export const SUBSECTION_PACKS_UNIT_35: FlawedQuestion[] = [
  // 3.5.1 Photosynthesis
  {
    id: 'pack-3-5-1',
    title: '3.5.1 Photosynthesis: Light-Dependent and Light-Independent Reactions',
    examBoard: 'AQA',
    specCode: '3.5.1',
    aqaUnit: '3.5',
    subject: 'AQA A-Level Biology (7402)',
    topic: '3.5.1 Photosynthesis (LDR & Calvin Cycle)',
    aoLevel: 'AO1 (3 marks) / AO2 (2 marks)',
    totalMarks: 5,
    questionText:
      'Describe how ATP and reduced NADP are produced in the light-dependent reaction of photosynthesis, and explain how they are used in the light-independent reaction to produce hexose sugar. (5 marks)',
    contextNote:
      'AQA Chief Examiner focus: Photoionisation of chlorophyll, electron transport chain creating proton gradient, chemiosmosis via ATP synthase, photolysis producing protons/electrons, and GP reduction using ATP and reduced NADP.',
    flawedAnswer:
      'Light hits the chlorophyll which excites water directly to make ATP. Electrons pass through the membrane creating oxygen. The reduced NADP and ATP then turn carbon dioxide into glucose directly in the stroma by fixing it with ribulose bisphosphate using rubisco without needing intermediate compounds.',
    officialMarkScheme: [
      {
        markCode: 'M1',
        criteria:
          'Light energy excites electrons in chlorophyll causing photoionisation, and electrons pass down electron transfer chain / carriers.',
        indicativePhrases: ['photoionisation of chlorophyll', 'electrons excited', 'electron transfer chain'],
        rejectOrErrors: 'Reject: light hits water directly to make ATP.',
      },
      {
        markCode: 'M2',
        criteria:
          'Energy released pumps protons into thylakoid space, establishing an electrochemical proton gradient; ATP generated by ATP synthase (photophosphorylation / chemiosmosis).',
        indicativePhrases: ['proton gradient across thylakoid', 'ATP synthase', 'chemiosmosis'],
        rejectOrErrors: 'Reject: ATP is made without ATP synthase or proton gradient.',
      },
      {
        markCode: 'M3',
        criteria:
          'Photolysis of water produces protons, electrons and oxygen (replacing chlorophyll electrons); NADP acts as terminal electron acceptor with protons to form reduced NADP (NADPH).',
        indicativePhrases: ['photolysis of water', 'H2O splits into H+, e- and O2', 'NADP reduced to NADPH'],
        rejectOrErrors: 'Reject: NADP reduced to NAD.',
      },
      {
        markCode: 'M4',
        criteria:
          'In Calvin cycle, carbon dioxide combines with ribulose bisphosphate (RuBP) catalysed by rubisco to produce two molecules of glycerate 3-phosphate (GP).',
        indicativePhrases: ['RuBP + CO2 -> 2 x GP', 'catalysed by rubisco', 'glycerate 3-phosphate'],
        rejectOrErrors: 'Reject: CO2 turns directly into glucose without GP / TP.',
      },
      {
        markCode: 'M5',
        criteria:
          'ATP (providing energy) and reduced NADP (providing hydrogen/electrons) are used to reduce GP to triose phosphate (TP); pairs of TP molecules are used to regenerate RuBP and synthesize hexose sugars.',
        indicativePhrases: ['reduction of GP to TP', 'using ATP and reduced NADP', 'TP regenerated to RuBP / hexose'],
        rejectOrErrors: 'Reject: GP converted directly to hexose without TP.',
      },
    ],
    flawedAnnotations: [
      {
        phrase: 'excites water directly to make ATP',
        issueType: 'misconception',
        explanation:
          'Water is split by photolysis (not excited directly); light energy excites electrons in chlorophyll leading to photoionisation.',
        markLost: 1,
        suggestedCorrection:
          'Light excites electrons in chlorophyll (photoionisation), and electrons pass along an electron transport chain.',
      },
      {
        phrase: 'Electrons pass through the membrane creating oxygen',
        issueType: 'misconception',
        explanation:
          'Oxygen is generated by the photolysis of water in the thylakoid lumen, not by electrons passing through membranes.',
        markLost: 1,
        suggestedCorrection:
          'Photolysis of water splits H2O into protons, electrons and oxygen (O2).',
      },
      {
        phrase: 'turn carbon dioxide into glucose directly in the stroma by fixing it with ribulose bisphosphate using rubisco without needing intermediate compounds',
        issueType: 'missing_keyword',
        explanation:
          'Completely omits the two vital 3-carbon intermediates: glycerate 3-phosphate (GP) and triose phosphate (TP).',
        markLost: 2,
        suggestedCorrection:
          'CO2 combines with RuBP to form 2x GP, which is reduced to TP using ATP and reduced NADP.',
      },
    ],
    examinerVerdict: {
      marksAwarded: 1,
      maxMarks: 5,
      summary:
        'Awarded 1/5 marks. Mentioned RuBP, rubisco and CO2 combination in stroma, but demonstrated severe misconceptions regarding photoionisation vs photolysis, and skipped all GP/TP reduction steps.',
    },
    exemplarRewrite:
      'Light energy excites electrons in chlorophyll during photoionisation, and they pass down an electron transport chain in the thylakoid membrane. Energy released pumps protons into the thylakoid lumen, and as protons diffuse back through ATP synthase down an electrochemical gradient, ATP is produced via chemiosmosis. Photolysis of water yields protons, electrons (to replace lost chlorophyll electrons), and oxygen; NADP accepts protons and electrons to form reduced NADP. In the stroma (Calvin cycle), carbon dioxide combines with RuBP catalysed by rubisco to form two molecules of glycerate 3-phosphate (GP). ATP and reduced NADP are then used to reduce GP into triose phosphate (TP), which is subsequently condensed to form hexose sugars and regenerate RuBP.',
    keyTerms: [
      'Photoionisation',
      'Electron transport chain',
      'Proton electrochemical gradient',
      'ATP synthase',
      'Photolysis of water',
      'Reduced NADP',
      'RuBP & Rubisco',
      'Glycerate 3-phosphate (GP)',
      'Triose phosphate (TP)',
    ],
    teacherNotes:
      'Crucial examiner trap: Students often say "ATP produces energy" instead of "ATP hydrolysis provides energy for GP reduction", and confuse photoionisation with photolysis.',
    recommendedColdCall:
      'What are the three products of the photolysis of water and where does each go in the chloroplast?',
  },

  // 3.5.2 Respiration
  {
    id: 'pack-3-5-2',
    title: '3.5.2 Respiration: Glycolysis, Link Reaction, Krebs Cycle & Oxidative Phosphorylation',
    examBoard: 'AQA',
    specCode: '3.5.2',
    aqaUnit: '3.5',
    subject: 'AQA A-Level Biology (7402)',
    topic: '3.5.2 Respiration (Aerobic & Anaerobic)',
    aoLevel: 'AO1 (3 marks) / AO2 (2 marks)',
    totalMarks: 5,
    questionText:
      'Describe the role of the cristae and inner mitochondrial membrane in oxidative phosphorylation, and explain how the oxidation of reduced NAD and reduced FAD results in the synthesis of ATP. (5 marks)',
    contextNote:
      'AQA Chief Examiner focus: Cristae provide large surface area for ETC proteins/ATP synthase, transfer of electrons releases energy, active transport of protons into intermembrane space, proton electrochemical gradient, chemiosmosis via ATP synthase, oxygen as terminal electron acceptor.',
    flawedAnswer:
      'The inner mitochondrial membrane folds into cristae to give space for the Krebs cycle. Reduced NAD and FAD give their electrons to oxygen at the start. Oxygen pumps hydrogen ions into the matrix, which causes heat to make ATP from ADP and phosphate.',
    officialMarkScheme: [
      {
        markCode: 'M1',
        criteria:
          'Cristae (folds of inner mitochondrial membrane) provide a large surface area for electron transport chains and ATP synthase enzymes.',
        indicativePhrases: ['large surface area', 'inner membrane cristae', 'for electron transfer chain / ATP synthase'],
        rejectOrErrors: 'Reject: cristae contain Krebs cycle enzymes (Krebs is in matrix).',
      },
      {
        markCode: 'M2',
        criteria:
          'Reduced NAD and reduced FAD are oxidised, releasing electrons to the electron transport chain and releasing protons (H+ ions).',
        indicativePhrases: ['oxidation of reduced NAD/FAD', 'release electrons to chain', 'release protons / H+'],
        rejectOrErrors: 'Reject: reduced NAD gives electrons directly to oxygen at start.',
      },
      {
        markCode: 'M3',
        criteria:
          'Electrons pass along the electron transfer chain in a series of oxidation-reduction reactions, releasing energy used to actively pump protons from the matrix into the intermembrane space.',
        indicativePhrases: ['electrons pass along carriers', 'energy pumps protons', 'into intermembrane space'],
        rejectOrErrors: 'Reject: protons pumped into matrix.',
      },
      {
        markCode: 'M4',
        criteria:
          'This establishes a proton electrochemical gradient (higher concentration in intermembrane space); protons diffuse back into matrix through ATP synthase via chemiosmosis, generating ATP from ADP and Pi.',
        indicativePhrases: ['proton electrochemical gradient', 'facilitated diffusion through ATP synthase', 'chemiosmosis forms ATP'],
        rejectOrErrors: 'Reject: heat directly synthesises ATP.',
      },
      {
        markCode: 'M5',
        criteria:
          'Oxygen acts as the terminal / final electron acceptor, combining with electrons and protons to form water (1/2 O2 + 2e- + 2H+ -> H2O).',
        indicativePhrases: ['oxygen is final electron acceptor', 'combines with electrons and protons', 'forms water'],
        rejectOrErrors: 'Reject: oxygen is initial acceptor.',
      },
    ],
    flawedAnnotations: [
      {
        phrase: 'cristae to give space for the Krebs cycle',
        issueType: 'misconception',
        explanation:
          'Krebs cycle takes place in the mitochondrial matrix, not on the cristae; cristae house the electron transfer chain and ATP synthase.',
        markLost: 1,
        suggestedCorrection:
          'Cristae provide a large surface area for electron transport chains and ATP synthase complexes.',
      },
      {
        phrase: 'Reduced NAD and FAD give their electrons to oxygen at the start',
        issueType: 'misconception',
        explanation:
          'Oxygen is the terminal (final) electron acceptor at the very end of the transport chain, not at the start.',
        markLost: 1,
        suggestedCorrection:
          'Electrons are passed to carrier proteins in the electron transfer chain; oxygen acts as the final electron acceptor.',
      },
      {
        phrase: 'causes heat to make ATP from ADP and phosphate',
        issueType: 'misconception',
        explanation:
          'ATP is formed mechanically/chemically by proton motive force turning ATP synthase (chemiosmosis), not by heat.',
        markLost: 1,
        suggestedCorrection:
          'Proton electrochemical gradient drives ATP synthesis via chemiosmosis through ATP synthase.',
      },
    ],
    examinerVerdict: {
      marksAwarded: 1,
      maxMarks: 5,
      summary:
        'Awarded 1/5 marks. Recognised inner membrane cristae and ATP formation from ADP + Pi, but placed Krebs cycle in cristae, misidentified oxygen as the start acceptor, and omitted chemiosmosis.',
    },
    exemplarRewrite:
      'The inner mitochondrial membrane is folded into cristae to provide a large surface area for electron transport chains and ATP synthase enzymes. Reduced NAD and reduced FAD are oxidised, transferring high-energy electrons to the electron transport chain and releasing protons (H+). As electrons flow along successive carrier proteins in redox reactions, energy is released to actively pump protons from the matrix into the intermembrane space. This creates an electrochemical proton gradient. Protons diffuse back down their electrochemical gradient into the matrix through ATP synthase via chemiosmosis, catalysing the phosphorylation of ADP to ATP. Finally, oxygen acts as the terminal electron acceptor, binding with protons and electrons to form water, preventing the transport chain from stalling.',
    keyTerms: [
      'Cristae surface area',
      'Oxidation of reduced NAD/FAD',
      'Electron transport chain',
      'Proton pumping to intermembrane space',
      'Electrochemical gradient',
      'ATP synthase & chemiosmosis',
      'Terminal electron acceptor (Oxygen)',
      'Water formation',
    ],
    teacherNotes:
      'Top AQA Examiner trap: Many students write "protons are pumped into the matrix" instead of "into the intermembrane space". Emphasise matrix is low H+, intermembrane space is high H+.',
    recommendedColdCall:
      'Why would oxidative phosphorylation completely stop if there was no oxygen available in the cell?',
  },

  // 3.5.3 Energy and Ecosystems
  {
    id: 'pack-3-5-3',
    title: '3.5.3 Energy and Ecosystems: Gross and Net Primary Production & Efficiency',
    examBoard: 'AQA',
    specCode: '3.5.3',
    aqaUnit: '3.5',
    subject: 'AQA A-Level Biology (7402)',
    topic: '3.5.3 Energy and Ecosystems (NPP, GPP & Secondary Production)',
    aoLevel: 'AO1 (2 marks) / AO2 (2 marks)',
    totalMarks: 4,
    questionText:
      'Explain the relationship between Gross Primary Production (GPP) and Net Primary Production (NPP) in plants, and explain why the efficiency of energy transfer between trophic levels is typically low (around 10%). (4 marks)',
    contextNote:
      'AQA Chief Examiner focus: NPP = GPP - R formula, GPP as chemical energy store in plant biomass, respiratory losses (R) as heat, and why primary consumers only assimilate ~10% (indigestible material/faeces, excretion, respiration).',
    flawedAnswer:
      'GPP is the total sunlight falling onto a plant field. NPP is the amount of sunlight that gets used for photosynthesis. Energy transfer is low between trophic levels because plants absorb green light and reflect the rest, so animals get cold.',
    officialMarkScheme: [
      {
        markCode: 'M1',
        criteria:
          'Gross Primary Production (GPP) is the total chemical energy store in plant biomass in a given area / volume in a given time.',
        indicativePhrases: ['total chemical energy store in biomass', 'GPP is total energy fixed'],
        rejectOrErrors: 'Reject: GPP is the total sunlight falling on leaves.',
      },
      {
        markCode: 'M2',
        criteria:
          'Net Primary Production (NPP) is the chemical energy store remaining after respiratory losses to the environment are deducted: NPP = GPP - R.',
        indicativePhrases: ['NPP = GPP - R', 'energy left after respiratory losses', 'biomass available to primary consumers'],
        rejectOrErrors: 'Reject: NPP is sunlight used.',
      },
      {
        markCode: 'M3',
        criteria:
          'Low efficiency of transfer to consumers because not all organism/biomass is consumed (e.g. roots/bones/woody tissue).',
        indicativePhrases: ['not all biomass eaten', 'parts uneaten / inaccessible'],
        rejectOrErrors: 'Reject: green light reflection explains consumer trophic transfer.',
      },
      {
        markCode: 'M4',
        criteria:
          'Energy lost in faeces / undigested material / cellulose (indigestible) and energy lost as metabolic heat via consumer cellular respiration (N = I - (F + R)).',
        indicativePhrases: ['lost in faeces / egestion', 'respiratory heat loss', 'urine / excretion'],
        rejectOrErrors: 'Reject: energy is destroyed.',
      },
    ],
    flawedAnnotations: [
      {
        phrase: 'GPP is the total sunlight falling onto a plant field',
        issueType: 'misconception',
        explanation:
          'GPP is chemical energy stored in plant biomass created by photosynthesis, not incident sunlight.',
        markLost: 1,
        suggestedCorrection:
          'GPP is the total chemical energy store in plant biomass per unit area per unit time.',
      },
      {
        phrase: 'NPP is the amount of sunlight that gets used',
        issueType: 'misconception',
        explanation:
          'NPP is the chemical energy remaining in biomass after plant respiratory losses (R): NPP = GPP - R.',
        markLost: 1,
        suggestedCorrection:
          'NPP = GPP - R, representing the chemical energy available for plant growth and consumers.',
      },
      {
        phrase: 'plants absorb green light and reflect the rest, so animals get cold',
        issueType: 'misconception',
        explanation:
          'Reflects ignorance of ecological trophic efficiency: energy is lost via uneaten parts, egestion (faeces), and respiratory heat.',
        markLost: 1,
        suggestedCorrection:
          'Energy is lost via indigestible parts/faeces, unconsumed biomass, and heat from cellular respiration.',
      },
    ],
    examinerVerdict: {
      marksAwarded: 0,
      maxMarks: 4,
      summary:
        'Awarded 0/4 marks. Confused GPP with incident light, gave incorrect definition for NPP, and provided an unscientific explanation for trophic transfer inefficiency.',
    },
    exemplarRewrite:
      'Gross Primary Production (GPP) is the total chemical energy store in plant biomass in a given area in a given time resulting from photosynthesis. Net Primary Production (NPP) is the chemical energy store that remains after plant respiratory losses (R) are deducted, defined by the relationship NPP = GPP - R (this represents biomass available for plant growth and primary consumers). Energy transfer efficiency between trophic levels is typically low (~10%) because not all plant biomass is consumed (e.g. roots/stems), significant energy is lost in faeces/egestion due to indigestible cellulose, and extensive energy is lost as heat to the environment during animal cellular respiration and movement.',
    keyTerms: [
      'GPP (chemical energy store in biomass)',
      'NPP = GPP - R',
      'Respiratory losses (R)',
      'Biomass available to consumers',
      'Indigestible material / egestion in faeces',
      'Respiratory heat loss',
      'Unconsumed tissues',
    ],
    teacherNotes:
      'AQA Chief Examiner highlights students continually confusing GPP with incident solar radiation. Make students recite NPP = GPP - R.',
    recommendedColdCall:
      'State the algebraic formula for net production of consumers (N) and explain what each letter stands for.',
  },

  // 3.5.4 Nutrient Cycles (Nitrogen & Phosphorus)
  {
    id: 'pack-3-5-4',
    title: '3.5.4 Nutrient Cycles: The Nitrogen Cycle & Saprobionts',
    examBoard: 'AQA',
    specCode: '3.5.4',
    aqaUnit: '3.5',
    subject: 'AQA A-Level Biology (7402)',
    topic: '3.5.4 Nutrient Cycles (N-Cycle & Mycorrhizae)',
    aoLevel: 'AO1 (3 marks) / AO2 (1 mark)',
    totalMarks: 4,
    questionText:
      'Describe the roles of microorganisms in the nitrogen cycle in converting organic nitrogen compounds in dead organic matter into forms that can be absorbed by plants. (4 marks)',
    contextNote:
      'AQA Chief Examiner focus: Saprobiontic ammonification, extracellular digestion of proteins/DNA/urea, nitrifying bacteria (oxidation of ammonium to nitrite, then nitrate), anaerobic denitrifying bacteria as a trap.',
    flawedAnswer:
      'Saprobionts eat dead plants and turn nitrogen gas directly into nitrate. Nitrogen-fixing bacteria in the air decompose the proteins into ammonia. Then denitrifying bacteria make the soil fertile by turning nitrites into nitrates for plant roots.',
    officialMarkScheme: [
      {
        markCode: 'M1',
        criteria:
          'Saprobionts / saprobiontic microorganisms decompose organic nitrogen-containing compounds (e.g. proteins / amino acids / DNA / urea) in dead organic matter.',
        indicativePhrases: ['saprobionts decompose organic nitrogen', 'break down proteins / nucleic acids / urea'],
        rejectOrErrors: 'Reject: saprobionts turn nitrogen gas into nitrate.',
      },
      {
        markCode: 'M2',
        criteria:
          'Decomposition releases ammonium ions / ammonia into the soil by ammonification.',
        indicativePhrases: ['ammonification', 'release ammonium ions / NH4+'],
        rejectOrErrors: 'Reject: decomposition directly releases nitrates.',
      },
      {
        markCode: 'M3',
        criteria:
          'Nitrifying bacteria in aerobic soil oxidise ammonium ions (NH4+) into nitrite ions (NO2-).',
        indicativePhrases: ['nitrifying bacteria', 'oxidise ammonium to nitrite'],
        rejectOrErrors: 'Reject: anaerobic conditions for nitrifying bacteria.',
      },
      {
        markCode: 'M4',
        criteria:
          'Further nitrifying bacteria oxidise nitrite ions into nitrate ions (NO3-), which are absorbed by plant root hair cells via active transport.',
        indicativePhrases: ['oxidise nitrite to nitrate', 'NO3- absorbed by plant roots'],
        rejectOrErrors: 'Reject: denitrifying bacteria turn nitrites into nitrates (denitrifying convert nitrate to N2 gas).',
      },
    ],
    flawedAnnotations: [
      {
        phrase: 'Saprobionts eat dead plants and turn nitrogen gas directly into nitrate',
        issueType: 'misconception',
        explanation:
          'Saprobionts perform extracellular digestion on organic proteins/DNA into ammonium ions, not atmospheric N2 gas.',
        markLost: 1,
        suggestedCorrection:
          'Saprobionts decompose nitrogen-containing compounds (proteins/DNA) into ammonium ions via ammonification.',
      },
      {
        phrase: 'Nitrogen-fixing bacteria in the air decompose the proteins into ammonia',
        issueType: 'misconception',
        explanation:
          'Nitrogen fixation reduces N2 gas to ammonia; saprobionts decompose proteins into ammonia.',
        markLost: 1,
        suggestedCorrection:
          'Saprobionts (not nitrogen fixers) break down organic nitrogen to release ammonium ions.',
      },
      {
        phrase: 'denitrifying bacteria make the soil fertile by turning nitrites into nitrates',
        issueType: 'misconception',
        explanation:
          'Fatal AQA trap: Denitrifying bacteria convert nitrates back into nitrogen gas (depleting soil fertility in waterlogged anaerobic soil). Nitrifying bacteria oxidise nitrites into nitrates.',
        markLost: 1,
        suggestedCorrection:
          'Nitrifying bacteria oxidise nitrites into nitrates; denitrifying bacteria do the opposite under anaerobic conditions.',
      },
    ],
    examinerVerdict: {
      marksAwarded: 0,
      maxMarks: 4,
      summary:
        'Awarded 0/4 marks. Mixed up every bacterial group in the nitrogen cycle: attributed N2 gas fixation to saprobionts and inverted the function of denitrifying bacteria.',
    },
    exemplarRewrite:
      'Saprobiontic microorganisms decompose organic nitrogen-containing compounds (such as proteins, amino acids, DNA, and urea) present in dead plant and animal matter. Through extracellular digestion, saprobionts secrete enzymes and release ammonium ions (NH4+) into the soil in the process of ammonification. Next, nitrifying bacteria in aerobic soil oxidise these ammonium ions into nitrite ions (NO2-). A second group of nitrifying bacteria subsequently oxidises nitrite ions into nitrate ions (NO3-). These nitrate ions can then be absorbed by plant root hair cells through active transport and incorporated into plant amino acids and nucleotides.',
    keyTerms: [
      'Saprobionts',
      'Extracellular digestion of proteins/DNA',
      'Ammonification (NH4+ release)',
      'Nitrifying bacteria',
      'Oxidation of ammonium to nitrite (NO2-)',
      'Oxidation of nitrite to nitrate (NO3-)',
      'Active transport into root hair cells',
    ],
    teacherNotes:
      'The #1 AQA examiner trap on the nitrogen cycle is confusing "nitrification" (ammonium -> nitrite -> nitrate by nitrifying bacteria) with "denitrification" (nitrate -> N2 gas by anaerobic denitrifying bacteria).',
    recommendedColdCall:
      'Why does soil aeration and ploughing increase the concentration of nitrates in farm soil?',
  },
];
